name: ✅ Quality Checks
on: [ push ]

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run checks
        uses: astral-sh/ruff-action@v1
        with:
          args: "check"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Try import
        run: |
          uv run python -c "import rapyuta_io_sdk_v2"

      - name: Install dependencies, activate uv environment, and run tests
        run: |
          uv sync 
          source .venv/bin/activate 
          pip install pytest pytest-cov
          pytest tests/